s3_bucket:
  train_data: wafer-train-data-5acbd2d
  logs: wafer-logs-4e1f3bd

dir:
  train_good_data: good/train
  log: wafer_data_transform_train/wafer_data_transform_train_logs/
  
col:
  output: Output
  good_bad: Good/Bad

log_params:
  filemode: a
  format: "%(asctime)s;%(levelname)s;%(file_name)s;%(class_name)s;%(method_name)s;%(message)s"
  datefmt: "%H:%M:%S"
  level: INFO
