- name: Setup application in instance
  hosts: Application_Group
  become: true
  vars_files:
    - /home/ubuntu/vars/variables.yml
  tasks:
    - name: Update using apt
      apt:
        update_cache: true

    - name: Update using apt-get
      apt:
        update_cache: true
        force_apt_get: true

    - name: Install pip3,nginx,gunicorn
      apt:
        name: 
          - python3-pip
          - nginx
          - gunicorn
        state: present
        
    - name: Initialize git
      shell: git init
      args:
        executable: /usr/bin/bash

    - name: Configure git
      shell: git config --global --add safe.directory /home/ubuntu

    - name: Get remote origin status
      shell: git remote show
      register: origin_status

    - name: Add remote origin
      block:
        - name: Add remote origin
          shell: git remote add origin https://github.com/sethusaim/Wafer-Fault-Kubernetes.git
          args:
            executable: /usr/bin/bash
      when: origin_status.stdout != "origin"

    - name: Fetch origin
      shell: git fetch origin
      args:
        executable: /usr/bin/bash

    - name: Check out application folder
      shell: git checkout origin/main -- application
      args:
        executable: /usr/bin/bash

    - name: Install requirements
      ansible.builtin.pip:
        requirements: /home/ubuntu/application/requirements.txt

    - name: Install gunicorn,passlib via pip3
      ansible.builtin.pip:
        name: 
          - gunicorn
          - passlib
        state: present

    - name: Install Apache Utils
      apt:
        name: apache2-utils
        update_cache: true
        force_apt_get: yes

    - name: Set user name and password for nginx
      community.general.htpasswd:
        path: /etc/nginx/.htpasswd
        name: "{{application.username}}"
        password: "{{application.password}}"

    - name: Copy the nginx configuration file
      ansible.builtin.copy:
        src: /home/ubuntu/flaskapp
        dest: /etc/nginx/sites-enabled/

    - name: Restart nginx service
      service:
        name: nginx
        state: restarted

    - name: Copy the application service file
      ansible.builtin.copy:
        src: /home/ubuntu/app.service
        dest: /etc/systemd/system/

    - name: Change permissions for sock file
      shell: sudo chown ubuntu:www-data /home/ubuntu/application/

    - name: Reload the daemon
      systemd:
        daemon_reload: yes

    - name: Enable app service
      systemd:
        name: app
        enabled: yes

    - name: Restart app service
      systemd:
        name: app
        state: restarted

    - name: Copy the secure app nginx file
      ansible.builtin.copy:
        src: /home/ubuntu/app
        dest: /etc/nginx/sites-enabled/

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    - name: Restart app service
      service:
        name: app
        state: restarted

    - name: Check whether node_exporter user exists or not
      shell: id node_exporter > /dev/null 2>&1 || echo not-exists
      register: user_exists

    - name: Add node_export user with no home directory
      block:
        - name: Add node_exporter user with no home directory
          shell: sudo useradd --no-create-home node_exporter
      when: user_exists.stdout == "not-exists"

    - name: Get the node export tar file
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        dest: /home/ubuntu

    - name: Untar the node exporter tar file
      shell: tar xzf node_exporter-1.3.1.linux-amd64.tar.gz

    - name: Copy the node exporter files to /usr/local/bin/node_exporter
      shell: sudo cp node_exporter-1.3.1.linux-amd64/node_exporter /usr/local/bin/node_exporter

    - name: Remove the node exporter files
      shell: rm -rf node_exporter-1.3.1.linux-amd64.tar.gz node_exporter-1.3.1.linux-amd64

    - name: Copy the node exporter service file
      ansible.builtin.copy:
        src: /home/ubuntu/node-exporter.service
        dest: /etc/systemd/system/

    - name: Reload the daemon
      systemd:
        daemon_reload: yes

    - name: Start and Enable the node exporter service
      systemd:
        name: node-exporter
        state: started
        enabled: yes
