- name: Setup Jenkins
  hosts: Jenkins_Group
  roles:
  - cloudalchemy.node_exporter
  become: true
  tasks:
    - name: Update using apt
      apt:
        update_cache: true

    - name: Update using apt-get
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add Jenkins Repositry Key
      apt_key: 
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key 
        state: present
      
    - name: Configure Jenkins Repositry
      apt_repository: 
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/' 
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        update_cache: true

    - name: Check Jenkins Installation
      service:
        name: jenkins
        state: started

    - name: Get Jenkins initial password
      shell: sudo cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_initial_password
      run_once: true

    - debug:
        msg: "Jenkins initial password : {{jenkins_initial_password.stdout}}"