dir:
  trained_model: trained
  stag_model: staging
  prod_model: production

model_save_format: .sav

mlflow_config:
  exp_name: wafer

feature_pattern: wafer_train_features-

s3_bucket:
  model: wafer-model-3e502a3
  feature_store: wafer-feature-store-02126f6

log_params:
  filemode: a
  format: "%(asctime)s;%(levelname)s;%(file_name)s;%(class_name)s;%(method_name)s;%(message)s"
  datefmt: "%H:%M:%S"
  level: INFO
