s3_bucket:
  io_files: wafer-io-files-03e0100
  logs: wafer-logs-4e1f3bd
  raw_pred_data: wafer-raw-data-140436f
  pred_data: wafer-pred-data-2648352

dir:
  raw_pred_batch_data: pred_batch
  pred_good_data: good/pred
  pred_bad_data: bad/pred

files:
  pred_schema: wafer-schema_prediction.json
  regex: wafer-regex.txt

log_params:
  filemode: a
  format: "%(asctime)s;%(levelname)s;%(file_name)s;%(class_name)s;%(method_name)s;%(message)s"
  datefmt: "%H:%M:%S"
  level: INFO
